### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by krt16s** [vi/redscreen.apk#1]
You released a 1.1, but the versioncode and versionname are still at 1 and 1.0 in AndroidManifest.xml . At least the versioncode integer should be bumped on every release, since it is used to check for updates. For details, see https://developer.android.com/tools/publishing/versioning.html

**Comment by vi** [comment]
Created tag v1.1.1 with fixed AndroidManifest.xml (`android:versionCode="2", android:versionName="1.1"`).

**Comment by krt16s** [comment]
Thanks for the fix.
